name: bedrive
description: Mobile application for BeDrive.
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.2
  package_info_plus: ^6.0.0
  yaml: ^3.1.2
  equatable: ^2.0.5
  background_downloader: ^8.4.1
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.8.0
  firebase_core: ^2.28.0
  intl: any
  email_validator: ^2.1.17
  device_info_plus: ^10.0.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  flutter_contacts: ^1.1.7+1
  date_field: ^5.0.1
  share_plus: ^8.0.3
  url_launcher: ^6.2.6
  open_file: ^3.3.2
  video_player: ^2.8.6
  chewie: ^1.8.1
  flutter_pdfview: ^1.3.2
  webview_flutter: ^4.7.0
  path: ^1.9.0
  path_provider: ^2.1.3
  drift: ^2.17.0
  drift_dev: ^2.17.0
  sqlite3_flutter_libs: ^0.5.21
  sqlite3: ^2.4.2
  uuid: ^4.4.0
  background_fetch: ^1.3.3
  flutter_launcher_icons: ^0.13.1
  sentry_flutter: ^8.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/social-logos/
    - assets/config/
    - app_config.yaml

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/logos/android-app-icon.png"
  image_path_ios: "assets/logos/ios-app-icon.png"
  adaptive_icon_background: "#1565c0"
  adaptive_icon_foreground: "assets/logos/android-app-icon.png"